### DISCUSSION TITLE
Dockerize Storage

### DISCUSSION THREAD

**Discussion by faqndo97** [joemasilotti/railsdevs.com#492] [Ideas]
Hi! 

I just forked the project and I'm seeing we need to install **Postgres** and **Redis** for the project. One tactic that I've been using for some time is to have a `docker-compose.yml` just to initialize the storage (**Postgres** and **Redis** in this case).

Here is an example of a `docker-compose` from another project. Pretty simple and small but reduce the number of things to have installed in the devs' machine and ensure everyone uses the same versions of them.

```yaml
version: '3'

services:
  postgres:
    image: postgres:13
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    volumes:
      - redis_data:/data
volumes:
  pg_data: {}
  redis_data: {}
```

Would you be interested in adding this here?
