### DISCUSSION TITLE
Where to put the stripe credentials?

### DISCUSSION THREAD

**Discussion by afrieirham** [joemasilotti/railsdevs.com#762] [Q&A] [answered]
Hi everyone, 

I'm trying to run the project locally but got stuck in Stripe setup, I'm not sure where to put the credentials mentioned [here](https://github.com/joemasilotti/railsdevs.com#stripe).

I tried placing it in `config/credentials/development.yml.enc` but it's not working.

Also, I'm very new to ruby, never have done this before. 👶🏻

**Comment by joemasilotti** [comment, marked as answer]
Decrypt the development credentials with:

```
$ bin/rails credentials:edit --environment development
```

That should open your editor to a plaintext file with all of the local secrets. Add your Stripe keys as the docs mention:

```yaml
stripe:
  private_key: XXX
  reporting_key: XXX
  price_ids:
    foo: XXX
    bar: XXX
```
