### ISSUE TITLE
Interested in linting erb with standardrb?

### ISSUE THREAD

**Issue by pingortle** [joemasilotti/railsdevs.com#67]
Love that this project uses standardrb. How about linting your erb files too?

I recently set up a new Rails app with a pretty minimal erblint config using standardrb for embedded ruby code. Happy to contribute PR if desired!

- https://github.com/Shopify/erb-lint

`cat .erb-lint.yml | pbcopy`
👇
```yaml
---
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true

  Rubocop:
    enabled: true
    rubocop_config:
      require: standard
      inherit_gem:
        standard: config/base.yml
      AllCops:
        DisabledByDefault: true
      Style/IdenticalConditionalBranches:
        Enabled: false
      Layout/BlockAlignment:
        Enabled: false
      Layout/HashAlignment:
        Enabled: false
      Layout/IndentationConsistency:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/IndentationWidth:
        Enabled: false
      Layout/LeadingEmptyLines:
        Enabled: false
      Layout/ParameterAlignment:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Lint/Void:
        Enabled: false
```
